# -*- coding: utf-8 -*-
"""train_rg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjCD--UIUntjwd4rjn54aeh_TW9UWJh4
"""

import sys
import os
!{sys.executable} -m pip install stable-baselines3 gymnasium[atari] autorom[accept-rom-license]
import ale_py.roms

from stable_baselines3 import DQN
from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy

import torch
import numpy as np
import random

def set_seed(seed=42):
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

import os
os.makedirs("models", exist_ok=True)

def create_env(n_stack=4, seed=42):
    env = make_atari_env("ALE/Galaxian-v5", n_envs=1)
    if n_stack > 1:
        env = VecFrameStack(env, n_stack=n_stack)
    return env

baseline_params = {
    "learning_rate": 1e-4,
    "gamma": 0.99,
    "batch_size": 32,
    "exploration_fraction": 0.3,
    "exploration_final_eps": 0.02,
    "train_freq": 4,
    "gradient_steps": 1,
    "target_update_interval": 1000,
    "buffer_size": 100000,
    "n_stack": 4
}

results = []

experiments = [
    ("baseline", baseline_params),

    ("lr_high", {**baseline_params, "learning_rate": 5e-4}),
    ("explore_more", {**baseline_params, "exploration_fraction": 0.5, "exploration_final_eps": 0.1}),
]

for name, params in experiments:
    print(f"Running: {name}")

    set_seed(42)
    env = create_env(n_stack=params["n_stack"], seed=42)

    model = DQN(
        "CnnPolicy",
        env,
        learning_rate=params["learning_rate"],
        gamma=params["gamma"],
        batch_size=params["batch_size"],
        buffer_size=params["buffer_size"],
        exploration_fraction=params["exploration_fraction"],
        exploration_final_eps=params["exploration_final_eps"],
        train_freq=params["train_freq"],
        gradient_steps=params["gradient_steps"],
        target_update_interval=params["target_update_interval"],
        verbose=0
    )

    model.learn(total_timesteps=30000)  # reduce for speed

    eval_env = create_env(n_stack=params["n_stack"], seed=43)
    mean_reward, std_reward = evaluate_policy(model, eval_env, n_eval_episodes=5)

    print(f"{name} → Mean reward: {mean_reward:.2f} ± {std_reward:.2f}")

    model.save(f"models/{name}.zip")

    results.append({
        "name": name,
        "mean_reward": mean_reward,
        "std_reward": std_reward
    })
    env.close()
    eval_env.close()

import pandas as pd
pd.DataFrame(results).to_csv("results.csv", index=False)

import os
os.makedirs("models", exist_ok=True)

def create_env(n_stack=4, seed=42):
    env = make_atari_env("ALE/Galaxian-v5", n_envs=1, seed=seed)
    if n_stack > 1:
        env = VecFrameStack(env, n_stack=n_stack)
    return env

baseline_params = {
    "policy": "CnnPolicy",
    "learning_rate": 1e-4,
    "gamma": 0.99,
    "batch_size": 32,
    "exploration_fraction": 0.3,
    "exploration_final_eps": 0.02,
    "train_freq": 4,
    "gradient_steps": 1,
    "target_update_interval": 1000,
    "buffer_size": 100000,
    "n_stack": 4
}

experiments = [
    ("baseline", baseline_params),

    ("buffer_less", {
        **baseline_params,
        "buffer_size": 50000
    }),

    ("more_train", {
        **baseline_params,
        "train_freq": 1,
        "gradient_steps": 4
    }),

    ("less_train", {
        **baseline_params,
        "train_freq": 8,
        "gradient_steps": 1
    }),

    ("gradient_clipping", {
        **baseline_params,
        "max_grad_norm": 1.0
    }),

     ("architecture_control", {
         **baseline_params,
         "policy_kwargs": dict(net_arch=[512])
     }),

    ("gamma_low", {
        **baseline_params,
        "gamma": 0.5
    }),

    ("gamma_mid", {
        **baseline_params,
        "gamma": 0.97
    }),

    ("very_low_explore", {
    **baseline_params,
    "exploration_fraction": 0.05,
    "exploration_final_eps": 0.005
    }),

    ("batch_small", {
    **baseline_params,
    "batch_size": 16
    })
]

results = []

best_model = None
best_reward = -np.inf

for name, params in experiments:
    print(f"Running: {name}")

    set_seed(42)
    env = create_env(n_stack=params["n_stack"], seed=42)
    policy_kwargs = params.get("policy_kwargs", None)
    max_grad_norm = params.get("max_grad_norm", 10)

    model = DQN(
        params["policy"],
        env,
        learning_rate=params["learning_rate"],
        gamma=params["gamma"],
        batch_size=params["batch_size"],
        buffer_size=params["buffer_size"],
        exploration_fraction=params["exploration_fraction"],
        exploration_final_eps=params["exploration_final_eps"],
        train_freq=params["train_freq"],
        gradient_steps=params["gradient_steps"],
        target_update_interval=params["target_update_interval"],
        verbose=0,
        policy_kwargs=policy_kwargs,
        max_grad_norm=max_grad_norm,
    )

    model.learn(total_timesteps=200000)  # increased to improve performance

    eval_env = create_env(n_stack=params["n_stack"], seed=43)
    mean_reward, std_reward = evaluate_policy(model, eval_env, n_eval_episodes=10)

    print(f"{name} → Mean reward: {mean_reward:.2f} ± {std_reward:.2f}")

    model.save(f"models/{name}.zip")

    results.append({
        "name": name,
        "mean_reward": mean_reward,
        "std_reward": std_reward
    })

    if mean_reward > best_reward:
        best_reward = mean_reward
        best_model = model
        best_model.save("models/best_model.zip")

    env.close()
    eval_env.close()

import pandas as pd
pd.DataFrame(results).to_csv("results.csv", index=False)

import time
import numpy as np
import pandas as pd
def create_env(n_stack=4, seed=42):
    env = make_atari_env("ALE/Galaxian-v5", n_envs=1, seed=seed)
    if n_stack > 1:
        env = VecFrameStack(env, n_stack=n_stack)
    return env


baseline_params = {
    "policy": "CnnPolicy",
    "learning_rate": 1e-4,
    "gamma": 0.99,
    "batch_size": 32,
    "exploration_fraction": 0.3,
    "exploration_final_eps": 0.02,
    "train_freq": 4,
    "gradient_steps": 1,
    "target_update_interval": 1000,
    "buffer_size": 100000,
    "n_stack": 4
}

experiments = [
    ("baseline", baseline_params),
    ("buffer_less", {**baseline_params, "buffer_size": 50000}),
    ("more_train", {**baseline_params, "train_freq": 1, "gradient_steps": 4}),
    ("less_train", {**baseline_params, "train_freq": 8, "gradient_steps": 1}),
    ("gradient_clipping", {**baseline_params, "max_grad_norm": 1.0}),
    ("architecture_control", {**baseline_params, "policy_kwargs": dict(net_arch=[512])}),
    ("gamma_low", {**baseline_params, "gamma": 0.5}),
    ("gamma_mid", {**baseline_params, "gamma": 0.97}),
    ("very_low_explore", {**baseline_params, "exploration_fraction": 0.05, "exploration_final_eps": 0.005}),
    ("batch_small", {**baseline_params, "batch_size": 16})
]

def build_description(name, params, baseline_params):
    changes = []

    for key in params:
        if key in baseline_params and params[key] != baseline_params[key]:
            changes.append(f"{key}: {baseline_params[key]} → {params[key]}")

    change_text = ", ".join(changes) if changes else "No changes"

    explanation_map = {
        "baseline": "Baseline configuration with default hyperparameters",
        "buffer_less": "Tests effect of smaller replay buffer (less memory diversity)",
        "more_train": "More frequent updates to learn faster",
        "less_train": "Less frequent updates to reduce overfitting",
        "gradient_clipping": "Stabilizes training by limiting gradient size",
        "architecture_control": "Tests impact of larger neural network",
        "gamma_low": "Focuses on short-term rewards",
        "gamma_mid": "Balances short-term and long-term rewards",
        "very_low_explore": "Reduces exploration, favors exploitation early",
        "batch_small": "Introduces noisier but faster updates"
    }

    explanation = explanation_map.get(name, "")
    return f"{explanation} | Changes: {change_text}"


models_dir = '/content'

print("Current directory:", os.getcwd())
print("Files in root:", os.listdir())

if not os.path.exists(models_dir):
    raise Exception("models' folder not found")

files = os.listdir(models_dir)
print("Files inside models:", files)

results = []

for i, (name, params) in enumerate(experiments):
    print(f"\n Looking for: {name}")

    # Smart match (handles weird filenames)
    match = [f for f in files if name in f and f.endswith(".zip")]

    if not match:
        print(f"Missing: {name}")
        continue

    model_file = match[0]
    model_path = os.path.join(models_dir, model_file)

    print(f"Found: {model_file}")

    start_time = time.time()

    env = create_env(n_stack=params["n_stack"], seed=43)
    model = DQN.load(model_path, env=env)

    # ---- Reward ----
    mean_reward, std_reward = evaluate_policy(
        model, env, n_eval_episodes=10, deterministic=True
    )

    # ---- Episode length ----
    episode_lengths = []
    for _ in range(10):
        obs = env.reset()
        done = False
        length = 0

        while not done:
            action, _ = model.predict(obs, deterministic=True)
            obs, reward, done, info = env.step(action)
            length += 1

        episode_lengths.append(length)

    mean_ep_length = np.mean(episode_lengths)
    elapsed_time = (time.time() - start_time) / 60

    print(f"{name}: {mean_reward:.2f} ± {std_reward:.2f}")

    # ---- Save row ----
    results.append({
        "Exp": f"Exp_{i+1}",
        "Policy": params["policy"],
        "lr": params["learning_rate"],
        "gamma": params["gamma"],
        "batch_size": params["batch_size"],
        "expl_fraction": params["exploration_fraction"],
        "expl_initial_eps": 1.0,
        "expl_final_eps": params["exploration_final_eps"],
        "Mean Reward": round(mean_reward, 2),
        "Std Reward": round(std_reward, 2),
        "Mean Ep Length": round(mean_ep_length, 2),
        "Time (min)": round(elapsed_time, 2),
        "Description": build_description(name, params, baseline_params)
    })

    env.close()


df = pd.DataFrame(results)
df.to_csv("results.csv", index=False)